### ISSUE TITLE
[SS3] Pressing enter creates new SiteConfig records instead of saving the existing one

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-siteconfig#106]
**CWP 1.9.3-rc2**

* Go to settings
* Change the site name
* Press enter

Expected: should save the record

Actual: creates and saves a new record

**Comment by maxime-rainville** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
