### ISSUE TITLE
"only these users" option is missing for access controls in SiteConfig

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-siteconfig#145]
In Silverstripe CMS 5.1 a new "only these users" option was added for inherited permissions. That option is missing from the access controls in SiteConfig.

## Related
- https://github.com/silverstripe/silverstripe-framework/issues/10817
- https://github.com/silverstripe/silverstripe-admin/issues/1609

## PRs
- https://github.com/silverstripe/silverstripe-siteconfig/pull/146

**Comment by sabina-talipova** [comment]
PR is merged. Issue was solved. Issue is closed.
