### ISSUE TITLE
Fix behat tests

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-siteconfig#29]
Post-namespace tests are failing. Possibly due to TinyMCE change detection, or possibly due to a real error introduced via namespacing.

**Comment by tractorcow** [comment]
I can confirm the tests pass fine locally.

  Scenario: I can change the theme of the website                                                      # siteconfig/tests/behat/features/settings-main.feature:27
    Given a theme "behattest"                                                                          # SilverStripe\Siteconfig\Test\Behaviour\ThemeContext::stepCreateTheme()
    And a template "Page.ss" in theme "behattest" with content "<h1>This is the behat test theme</h1>" # SilverStripe\Siteconfig\Test\Behaviour\ThemeContext::stepCreateTemplate()
    When I go to "/admin/settings"                                                                     # SilverStripe\Siteconfig\Test\Behaviour\FeatureContext::visit()
    Then I should see an edit page form                                                                # SilverStripe\Framework\Test\Behaviour\CmsFormsContext::stepIShouldSeeAnEditPageForm()
    And I should see "Theme"                                                                           # SilverStripe\Siteconfig\Test\Behaviour\FeatureContext::assertPageContainsText()
    When I select "behattest" from "Theme"                                                             # SilverStripe\Siteconfig\Test\Behaviour\FeatureContext::selectOption()
    And I press the "Save" button                                                                      # SilverStripe\BehatExtension\Context\BasicContext::stepIPressTheButton()
    And I go to "/home?flush=1"                                                                        # SilverStripe\Siteconfig\Test\Behaviour\FeatureContext::visit()
    Then I should see "This is the behat test theme"                                                   # SilverStripe\Siteconfig\Test\Behaviour\FeatureContext::assertPageContainsText()

2 scenarios (2 passed)
26 steps (26 passed)
0m26.766s
Killing test session environment...Deleted temp database: ss_tmpdb5397821
 done!

**Comment by dhensby** [comment]
Can we see the screenshot from the failed test?

Also, maybe it's a timeout issue? do we really need the ?flush parameter, there?

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5798

Ignore small issue with shortcodes being parsed; It'll be fixed with defaut_cast
