### ISSUE TITLE
Allow for field validation.

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-siteconfig#5]
Currently the `SiteConfig` abstraction doesn't allow for validation. This is a carryover from older issues in `silverstripe-cms` here: https://github.com/silverstripe/silverstripe-cms/issues/556 and a subsequent (now out of date PR) from here: https://github.com/silverstripe/silverstripe-cms/pull/1238

I'm currently working on a revision to this repository which will enable `SiteConfig` to automatically use validation on its own simply by having a `DataExtension` extending `SiteConfig` which may contain the standard `->getCMSValidator()` method.

**Comment by maxime-rainville** [comment]
Looks like this got fixed by https://github.com/silverstripe/silverstripe-siteconfig/pull/9
