### ISSUE TITLE
Validation errors are not focused.

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-siteconfig#7]
Relates to #5 and depends on PR #6

**Before:**
![before](https://cloud.githubusercontent.com/assets/4269377/10353039/74551fce-6d21-11e5-9b9e-3723c2bf8bfb.png)

**Desired after:**
![after](https://cloud.githubusercontent.com/assets/4269377/10353041/766334ae-6d21-11e5-856f-6bf4d023254c.png)

My hunch is that this would fix the validation error so it would focus to the correct tab.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
