### ISSUE TITLE
Siteconfig and CMS have clashing namespaces / class names

### ISSUE THREAD

**Issue by silbinarywolf** [silverstripe/silverstripe-siteconfig#81]
**Identical class names:**
https://github.com/silverstripe/silverstripe-siteconfig/blob/3.6/tests/behat/features/bootstrap/SilverStripe/Cms/Test/Behaviour/ThemeContext.php
https://github.com/silverstripe/silverstripe-cms/blob/3.6/tests/behat/features/bootstrap/SilverStripe/Cms/Test/Behaviour/ThemeContext.php

Composer just chooses the first one it finds when populating the `vendor/composer/autoload_classmap.php`

**Comment by tractorcow** [comment]
siteconfig doesn't even run behat tests; Let's remove these in the 3.6 branch to fix.

**Comment by robbieaverill** [comment]
Fixed in #83
