### ISSUE TITLE
Admin 1.0.2 upgrade seems to break javascript dependent fields in SiteConfig

### ISSUE THREAD

**Issue by mlewis-everley** [silverstripe/silverstripe-siteconfig#88]
This is quite a strange issue, but since upgrading `siteconfig` to 4.0.2 and `silverstripe-admin` to 1.0.2 some all Javascript based form fields stop functioning when you add a HTML Editor Field.

In the example below, the Upload Field renders as a standard `FileField` and the `TreeDropdownField` does not appear at all. If I remove the `HTMLEditorField` then the other fields render as expected:

````
<?php

use SilverStripe\Forms\TreeDropdownField;
use SilverStripe\Forms\HTMLEditorField;
use SilverStripe\Forms\FieldList;
use SilverStripe\ORM\DataExtension;
use SilverStripe\Assets\Image;
use SilverStripe\AssetAdmin\Forms\UploadField;

class AppSiteConfig extends DataExtension
{
    private static $db = [
        'SomeHTML' => 'HTMLText'
    ];

    private static $has_one = [
        'Logo' => Image::class,
        'ContactPage' => ContactPage::class
    ];

    public function updateCMSFields(FieldList $fields)
    {
        $fields->addFieldToTab(
            'Root.Main',
            UploadField::create(
                "Logo",
                "Site Logo"
            )
        );

        $fields->addFieldToTab(
            'Root.Main',
            TreeDropdownField::create(
                "ContactPageID",
                "Link to 'contact' page",
                'ContactPage'
            )
        );

        $fields->addFieldToTab(
            'Root.Main',
            HTMLEditorField::create(
                "SomeHTML",
                "Some HTML"
            )
        );
    }
}
````

I have also checked the Javascript console, and get this error (which appears to be from `TreeDropdownField` and goes away if I remove the `HTMLEditorField`):

````
Uncaught TypeError: Cannot read property 'fields' of undefined
    at l (bundle.js?m=1516829605:1)
    at s.configureFinalMapState (vendor.js?m=1516829605:1)
    at s.computeStateProps (vendor.js?m=1516829605:1)
    at s.updateStatePropsIfNeeded (vendor.js?m=1516829605:1)
    at s.render (vendor.js?m=1516829605:1)
    at d._renderValidatedComponentWithoutOwnerOrContext (vendor.js?m=1516829605:1)
    at d._renderValidatedComponent (vendor.js?m=1516829605:1)
    at d.performInitialMount (vendor.js?m=1516829605:1)
    at d.mountComponent (vendor.js?m=1516829605:1)
    at Object.mountComponent (vendor.js?m=1516829605:1)
````

All other JS appears to load as normal.

If I downgrade the silverstripe-admin module to 1.0.1 then everything works as expected :-s.

I have tried to trace this in some more detail, but to be honest I am quite stumped, I am not 100% sure if this is a `siteconfig` issue or a `silverstripe-admin` issue

**Comment by robbieaverill** [comment]
This issue was fixed recently in the admin module - see https://github.com/silverstripe/silverstripe-framework/issues/7806

**Comment by mlewis-everley** [comment]
OK, I will keep an eye on the next release stable release, hopefully that will solve these issues then :-)
