### ISSUE TITLE
Objects owned by SiteConfig won't publish on save

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-siteconfig#92]
Even though `SiteConfig extends DataObject` and therefore has the `RecursivePublishable` extension, it won't publish anything it `$owns` on save, because it is using a [custom form action](https://github.com/silverstripe/silverstripe-siteconfig/blob/4/code/SiteConfig.php#L238-L254).

Simple fix is to check for the extension in that method (I'll PR that shortly) but it's probably worth looking at whether we can standardise it into a more normal DO.

**Comment by maxime-rainville** [comment]
Correct me if I'm wrong here, but SiteConfig isn't Versionned ... so it can't be published.

Wouldn't that preclude it from recursively publishing child DataObject?

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-siteconfig/pull/93
