### ISSUE TITLE
SiteConfig with RecursivePublishable Extension does not save changes

### ISSUE THREAD

**Issue by youpixxl** [silverstripe/silverstripe-siteconfig#95]
After updating to dev-master version I wasn't able to save changes in SiteConfig.
I found out this was due to new lines in SiteConfigLeftAndMain save_siteconfig(). 

` if ($siteConfig->hasExtension(RecursivePublishable::class)) {
            $siteConfig->publishRecursive();
        } else {
            $siteConfig->write();
        };`

I had to roll back to previous version

# PRs:

- [ ] https://github.com/silverstripe/silverstripe-siteconfig/pull/96

**Comment by dhensby** [comment]
`dev-master` is the 5.x compatible line; are you developing with SS 5? What version did you rollback to?

We would never recommend using `dev-master` constraint anywhere as it's very risky and dependencies and other constraints changing can be a big problem.

**Comment by tractorcow** [comment]
It's a real bug in 4.x too. We still need the write EVEN if we do a publishRecursive() after.

**Comment by tractorcow** [comment]
Example of correct code from CMSMain.

```php
// save form data into record
        $form->saveInto($record);
        $record->write();

        // If the 'Publish' button was clicked, also publish the page
        if ($doPublish) {
            $record->publishRecursive();
```

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-siteconfig/pull/96
