### ISSUE TITLE
Unable to save new data in any siteconfig fields

### ISSUE THREAD

**Issue by monkeyfeet** [silverstripe/silverstripe-siteconfig#98]

**Comment by NightJar** [comment]
@monkeyfeet can you please provide the versions of the framework, admin, and this module that you have installed?
The output of `composer show` can tell you this information, if you're unsure how to obtain it.

**Comment by maxime-rainville** [comment]
Just had a chat with @tractorcow. It's been fixed already, but it hasn't merged back into the main 4 branch. https://github.com/silverstripe/silverstripe-siteconfig/pull/96

He'll get it merged in and it should be available in the dev 4 branch _soonish_.

**Comment by NightJar** [comment]
Is there any indication on what versions this affects, if any (is it just unstable HEAD)?

**Comment by maxime-rainville** [comment]
@NightJar It was merged into 4.1 originally. It should have been merged into 4 automatically when we did the 4.2 release last week.

**Comment by NightJar** [comment]
Right, cool. So it doesn't affect any released version?

**Comment by tractorcow** [comment]
4.2.0-beta1 has this bug. rc1 / beta2 will fix it.

**Comment by maxime-rainville** [comment]
Nothing left to do on this. I'll close.
